// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_training/test/unit/repository/weather_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_training/data/datastore/weather_datastore.dart' as _i3;
import 'package:flutter_training/data/model/weather/weather_forecast_target.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:yumemi_weather/yumemi_weather.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeYumemiWeather_0 extends _i1.SmartFake implements _i2.YumemiWeather {
  _FakeYumemiWeather_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherDatastore].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherDatastore extends _i1.Mock implements _i3.WeatherDatastore {
  @override
  _i2.YumemiWeather get weatherClient => (super.noSuchMethod(
        Invocation.getter(#weatherClient),
        returnValue: _FakeYumemiWeather_0(
          this,
          Invocation.getter(#weatherClient),
        ),
        returnValueForMissingStub: _FakeYumemiWeather_0(
          this,
          Invocation.getter(#weatherClient),
        ),
      ) as _i2.YumemiWeather);
  @override
  Map<String, dynamic> getWeather(_i4.WeatherForecastTarget? target) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [target],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
  @override
  String toJson(_i4.WeatherForecastTarget? target) => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [target],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  Map<String, dynamic> toMap(String? json) => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [json],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
